/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartDrawer: typeof import('./src/components/CartDrawer.vue')['default']
    EmptyCart: typeof import('./src/components/EmptyState.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    FavoritesDrawer: typeof import('./src/components/FavoritesDrawer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MovieCard: typeof import('./src/components/MovieCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
